# Generated by Django 4.0.4 on 2022-08-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0004_alter_post_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='subject',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
