# Generated by Django 4.0.4 on 2022-08-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0005_comment_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rareuser',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
