# Generated by Django 4.0.4 on 2022-08-18 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0006_alter_rareuser_active'),
        ('app_api', '0007_alter_subscription_ended_on'),
    ]

    operations = [
    ]
